Tfo.Finance.Web/Controllers/IssuerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tfo.Finance.Domain.Abstract;
using Tfo.Finance.Domain.Entities;

namespace Tfo.Finance.Web.Controllers
{
    public class IssuerController : Controller
    {
        private IIssuerProvider _issuerProvider;

        public IssuerController(IIssuerProvider issuerProvider)
        {
            _issuerProvider = issuerProvider;
        }

        // GET: Issuer
        public ActionResult Search()
        {
            return View(new Stock());
        }

        [HttpPost]
        public ActionResult Display(Stock stock)
        {
            var issuer = _issuerProvider.GetIssuer(stock.Symbol.ToUpper());
            return View(issuer);
        }
    }
}

Tfo.Finance.Web/Views/Issuer/Display.cshtml
@model Tfo.Finance.Domain.Entities.Issuer

@{
    ViewBag.Title = "Stock and Option Information for " + @Model.Description;
}

<h2>@Model.Description</h2>

<h3>Stock Information</h3>
<table class="table">
    <thead>
        <tr>
            <td>Symbol</td>
            <td>Description</td>
            <td>Bid</td>
            <td>Ask</td>
            <td>Last</td>
            <td>Updated</td>
        </tr>
    </thead>
    <tr>
        @foreach (var stock in Model.Securities.OfType<Tfo.Finance.Domain.Entities.Stock>())
        {
            <td>@stock.Symbol</td>
            <td>@stock.Description</td>
            <td>@stock.Quote.Bid</td>
            <td>@stock.Quote.Ask</td>
            <td>@stock.Quote.Last</td>
            <td>@stock.Quote.UpdateTime</td>
        }
    </tr>
</table>

<h3>Option Information</h3>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <td>Symbol</td>
            <td>Description</td>
            <td>Put/Call</td>
            <td>Strike</td>
            <td>Expiry</td>
            <td>Bid</td>
            <td>Ask</td>
            <td>Last</td>
            <td>Updated</td>
        </tr>
    </thead>
    @foreach (var option in Model.Securities.OfType<Tfo.Finance.Domain.Entities.Option>())
    {
        <tr>
            <td>@option.Symbol</td>
            <td>@option.Description</td>
            <td>@option.PutCall</td>
            <td>@option.Strike</td>
            <td>@option.Expiry.ToShortDateString()</td>
            <td>@option.Quote.Bid</td>
            <td>@option.Quote.Ask</td>
            <td>@option.Quote.Last</td>
            <td>@option.Quote.UpdateTime</td>
        </tr>
    }
</table>

Tfo.Finance.Web/Views/Issuer/Search.cshtml
@model Tfo.Finance.Domain.Entities.Stock

@{
    ViewBag.Title = "Search";
}

<body class="container">
    <div class="panel panel-primary">
        <h4 class="panel-heading text-center">Enter a Stock Symbol</h4>
        <div class="panel-body">
            @using (Html.BeginForm("Display", "Issuer"))
            {
                @Html.TextBoxFor(e => e.Symbol, new { @class = "form-control" })

                <div>
                    <button class="btn btn-primary center-block" type="submit">Submit</button>
                </div>
            }
        </div>
    </div>

</body>

Tfo.Finance.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>